# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogChangeExtensions.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialogChangeExtensions(object):
    def setupUi(self, dialogChangeExtensions):
        dialogChangeExtensions.setObjectName("dialogChangeExtensions")
        dialogChangeExtensions.resize(260, 154)
        self.verticalLayout = QtWidgets.QVBoxLayout(dialogChangeExtensions)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget_Extensions = QtWidgets.QListWidget(dialogChangeExtensions)
        self.listWidget_Extensions.setObjectName("listWidget_Extensions")
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget_Extensions.addItem(item)
        self.verticalLayout.addWidget(self.listWidget_Extensions)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pBtn_Ok = QtWidgets.QPushButton(dialogChangeExtensions)
        self.pBtn_Ok.setObjectName("pBtn_Ok")
        self.horizontalLayout.addWidget(self.pBtn_Ok)
        self.pBtn_Cancel = QtWidgets.QPushButton(dialogChangeExtensions)
        self.pBtn_Cancel.setObjectName("pBtn_Cancel")
        self.horizontalLayout.addWidget(self.pBtn_Cancel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(dialogChangeExtensions)
        QtCore.QMetaObject.connectSlotsByName(dialogChangeExtensions)

    def retranslateUi(self, dialogChangeExtensions):
        _translate = QtCore.QCoreApplication.translate
        dialogChangeExtensions.setWindowTitle(_translate("dialogChangeExtensions", "Изменить расширения..."))
        __sortingEnabled = self.listWidget_Extensions.isSortingEnabled()
        self.listWidget_Extensions.setSortingEnabled(False)
        item = self.listWidget_Extensions.item(0)
        item.setText(_translate("dialogChangeExtensions", "(Выделить всё)"))
        self.listWidget_Extensions.setSortingEnabled(__sortingEnabled)
        self.pBtn_Ok.setText(_translate("dialogChangeExtensions", "ОК"))
        self.pBtn_Cancel.setText(_translate("dialogChangeExtensions", "Отмена"))
